### ISSUE TITLE
Crash reports implementation?

### ISSUE THREAD

**Issue by nuno** [dieskim/countly-sdk-appcelerator-titanium-ios#1]
Hello, is Crash reports implementation is already in the modules?

Thanks

**Comment by dieskim** [comment]
Not yet - I should be able to build it in with some help from the Countly team and if I was able to raise some fund to pay for my time to do it that would make it happen even faster...

**Comment by nuno** [comment]
That's ok this features is not free one as I can see in they site. Thanks

**Comment by dieskim** [comment]
This has now been added - marking closed

**Comment by dieskim** [comment]
I wanted to let you know that Crash Reports are now open source - https://medium.com/@countly/we-are-open-sourcing-our-crash-analytics-dashboard-dacd913e5ec9

**Comment by nuno** [comment]
Thanks @dieskim for the info!
